from __future__ import annotations

import os


CHAT_HOST = os.getenv("STEALTH_CHAT_HOST", "0.0.0.0")
CHAT_PORT = int(os.getenv("STEALTH_CHAT_PORT", "54321"))
DISCOVERY_PORT = int(os.getenv("STEALTH_DISCOVERY_PORT", "54322"))
DISCOVERY_TIMEOUT = float(os.getenv("STEALTH_DISCOVERY_TIMEOUT", "1.5"))
DISCOVERY_RETRIES = int(os.getenv("STEALTH_DISCOVERY_RETRIES", "4"))
SERVER_NAME = os.getenv("STEALTH_CHAT_SERVER_NAME", "Stealth-Chat")

USERNAME_MIN_LEN = 3
USERNAME_MAX_LEN = 20
ROOM_MIN_LEN = 1
ROOM_MAX_LEN = 32
MAX_TEXT_LEN = int(os.getenv("STEALTH_CHAT_MAX_TEXT_LEN", "1000"))
MAX_AUTH_PAYLOAD_LEN = int(os.getenv("STEALTH_CHAT_MAX_AUTH_LEN", "256"))

AUTH_MAX_FAILURES = int(os.getenv("STEALTH_AUTH_MAX_FAILURES", "5"))
AUTH_WINDOW_SECONDS = int(os.getenv("STEALTH_AUTH_WINDOW_SECONDS", "60"))
AUTH_BLOCK_SECONDS = int(os.getenv("STEALTH_AUTH_BLOCK_SECONDS", "120"))

SOCKET_TIMEOUT = float(os.getenv("STEALTH_SOCKET_TIMEOUT", "20"))

HISTORY_ENABLED = os.getenv("STEALTH_HISTORY_ENABLED", "1") == "1"
HISTORY_DB_PATH = os.getenv("STEALTH_HISTORY_DB", "chat_history.db")
HISTORY_RETENTION_DAYS = int(os.getenv("STEALTH_HISTORY_RETENTION_DAYS", "7"))
HISTORY_MAX_MESSAGES = int(os.getenv("STEALTH_HISTORY_MAX_MESSAGES", "2000"))
